

jobs:
  include:
    - stage: stage 1
      before_script:
        - mkdir -p out/
        - ls -lahtR
      script: echo Stage 1 - Job 1
      cache:
        - directories:
          - ./out
      after_script:
        - echo $(date) > stage1_job1
        - ls -lRaht
    - before_script: ls -l
      script: echo Stage 1 - Job 2
      after_script: 
        - echo $(date) > stage1_job2
        - ls -lRaht

    - stage: stage 2
      env:
        - env1=$(date)
        - env2=100
      cache:
        - directories:
          - ./out
      before_script:
        - ls -lahtOR
      script: echo Stage 2 - Job 1
      after_script:
        - echo $(date) > out/stage2_job1
        - echo $env1 >> out/stage2_job1
        - echo $env2 >> out/stage2_job1
        - ls -lRaht
        - cat out/stage2_job1
  
    - stage: stage 3
      cache:
        - directories:
          - ./out
      before_script:
        - ls -lahtR
      script: echo Stage 3 - Job 1
      after_script:
        - echo $(date) > out/stage3_job1
        - ls -lRaht
    