

jobs:
  include:
    - stage: stage 1
      before_script: ls -l
      script: echo Stage 1 - Job 1
      after_script:
        - echo 1 > stage1_job1
        - ls -l
    - before_script: ls -l
      script: echo Stage 1 - Job 2
      after_script: 
        - echo 1 > stage1_job2
        - ls -l

    - stage: stage 2
      before_script: ls -l
      script: echo Stage 2 - Job 1
      after_script: echo 1 > stage2_job1
  
    - stage: stage 3
      before_script: ls -l
      script: echo Stage 3 - Job 1
      after_script: echo 1 > stage3_job1
      script: ls -l
    